### ISSUE TITLE
Run Tests without Sausage Package. 

### ISSUE THREAD

**Issue by vinnyalvs** [filesender/filesender#1140]
Hello. I work with the Brazilian National Research Network implantation of Filesender (https://filesender.rnp.br/), and we do some little customizations and we wanted to test them with Selenium. That said, we don't want to use the current tests implementations because:

- We don't want to use Sauce Labs
- We don't want to use the Sausage Package
- The tests use an old version of PHPUnit 

Hence, we build a new Base class for Selenium Tests, updated the tests to run with newer PHPUnit versions, and changes the requirements in composer.json File. We made a pull request with these modifications, and we want to discuss what is best for the project.  We did not want to break what currently exists, so we created new files instead of replacing old ones. 

I don't know if this is the best place to ask this, but we want to know **why** did you choose to use the Sausage Package and **why** do you run the selenium tests in another repository.

**Comment by monkeyiq** [comment]
Hello and welcome!

This is a good place to ask the above. Either here on the dev mailing list. The selenium tests are run in another repository because they are managed by savage which checks if somebody is trying to update the test suite to do nasty things. The selenium test suite needs to contact sauce labs so it is a good idea to do some checks before running tests from PRs from unknown sources.

The sausage package was there when I arrived. Not a great answer but the only one I have. I tried at one point to update to more recent versions for the test suite but met with resistance on the sauce labs connection so left it where it was for now. I would be happy to use a newer version of phpunit.

A partial fragment of my /opt/filesender/config/config.php on the selenium test VM:

```
  $config['testsuite_run_locally'] = true;
  $config['auth_sp_type'] = 'fake';
  $config['auth_sp_fake_authenticated'] = true;
  $config['auth_sp_fake_uid'] = 1;
  $config['auth_sp_fake_email'] = 'memoryhole@localhost.localdomain';
```

This VM runs the tests locally without Sauce Labs. I also set a sauce username though that shouldn't be used because a local Chrome in the same VM is used to run the test pass.

```
export SAUCE_USERNAME=ben
```
