### ISSUE TITLE
Possible GPG/PGP use

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#1249]
As FileSender offers to email the recipient it should be possible to integrate some public key cryptography to encrypt the passphrase used to encrypt the filesender transfer. Such integration might start out a little clunky, with a recipient needing to manually upload their public key to enable the feature. If the GPG/PGP happens completely in browser this could make it easier to encrypt more files without needing to explicitly communicate the passphrase over a secure channel.

With this a user can allow people to send encrypted files to them without needing to setup a shared passphrase book before sending files. This then relies on the security of both FileSender encryption and that of PGP/GPG.

A workflow might be as follows. 
* A user Bob logs into FileSender and goes to the profile page and uploads their public key.
* Alice logs into the server and wants to send a file to Bob with encryption
* After adding the files Alice deselects the "Get a link" option to be able to enter Bob's email address
* When alice confirms Bob's address a new button appears to allow the passphrase to be generated and included in the encrypted message body. 
* Alice elects to do that
* The encrypted message is generated replaces the text message to be emailed to Bob. This is done completely in the browser. The passphrase used by FileSender to encrypt the files never leaves the local browser that Alice is using.
* The upload is then performed and completed
* Bob gets a GPG/PGP encrypted email which when decrypted contains the password that FileSender generated and used to encrypt the transfer.
* Bob's email client decrypts that email and so Bob can then go and download the file(s) from the FileSender server using the passphease.

**Comment by monkeyiq** [comment]
I am thinking such an option might be useful for guests. Especially if they can only send to the person who invited them. If this public key option is forced on then the guest would only need to add file(s) and submit. They would be encrypted and the passphrase securely emailed to the person who invited the guest automatically. An interesting part to the design IMHO is that the uploading person doesn't need to know about PKI or have software or keys installed to use it in the browser.

**Comment by monkeyiq** [comment]
Having a key in the system itself allows a future update to include a script to possibly look for a person's public key and import it automatically or offer to do so on the profile page.

**Comment by WebSpider** [comment]
I really like the idea of having a form of seamless encryption in filesender based on previously known keys, and it's an idea that I known research hours are being put into at this very moment.

By changing the encryption we have/allow/can use we:
1. Have ways to improve portability of clients (not every environment has easy access to a webserver, and not all datasets are suitable for loading into a webservers memory)
2. Might pick something that's industry standard, with the advantages that come with it =)

My personal favorite would not be classic OpenPGP approach, but that's mainly due to the key distribution problems there are in the world at the moment, which are not limited to identiy spoofing, certificate flooding and off course the issue that many European key servers are really struggling to keep their service going with the GDPR active.

Many rights introduced in the GDPR are a bit contrary to the assumptions that key servers make, and things like the right to be forgotten are downright problematic.

BUT

I do think the pros outweigh the cons here: Having encryption options opens new doors for filesender. If a good first implementation for this is OpenPGP, two thumbs up.

**Comment by monkeyiq** [comment]
I have received some feedback that this would be a useful feature from a few places now. Not direct mentions on this gh issue but...
