### ISSUE TITLE
Filesender Setup Video

### ISSUE THREAD

**Issue by baybarshan008** [filesender/filesender#1304]
Is there a Filesender Installation Video? Can you give me a URL if you have one? I'm trying to set it up, but I've been making mistakes for days. I'm freaking out.

**Can you make a setup video, please? I need it too much.**

**Comment by dxdemetriou** [comment]
> Is there a Filesender Installation Video? Can you give me a URL if you have one? I'm trying to set it up, but I've been making mistakes for days. I'm freaking out.
> 
> **Can you make a setup video, please? I need it too much.**

According to the installation guide:
https://docs.filesender.org/filesender/v2.0/install/

it's not easily possible to be shown on a video how to install it  (and I doubt if anybody will spend their time on this), as there are many configurations for every need, and because of the authentication method in which except that the used method is a different project, you have to find it by yourself depending of your needs how should be configured. And the main reason: it's not just "install and play", there should be a knowledge of everything described in the installation guide or you should start reading and learning them.

The most complex part is the "Step 4 - Install and configure SimpleSAMLphp", in which is better to try to understand this part first, and the better way is by trying building some virtual machines and playing with snapshots.
