### ISSUE TITLE
2.0 installation instructions refer to nonexistant 1.x configuration

### ISSUE THREAD

**Issue by Farmbuyer** [filesender/filesender#1320]
The instructions at https://docs.filesender.org/filesender/v2.0/install/ step 7 for PHP have this cautionary line:

> upload_tmp_dir = /tmp
>
> NOTE: You probably want to point this to the same directory you will use as your HTML5 upload temp directory ($config['site_temp_filestore']).

The same advice appears in the example config files `config-templates/filesender-php.ini` and `ci/php-config.ini`.

I can't find a setting for `site_temp_filestore` anywhere.  The `docs/v2.0/development-upgrade-notes/index.md` file has a list of config directives that don't exist any longer; the list has `site_tempfilestore` (note the different spelling) with an explanation of only _"use different way of storing files"_, so I'm guessing the config went away, the 2.0 instructions were never updated, and the entry in the upgrade notes is a small typo.

So, that leaves two questions:

1. What $config setting _should_ `upload_tmp_dir` match in the current version, now that site_temp_filestore is gone?
2. If we're using Amazon S3 as a backing store instead of `storage_type = filesystem`, how does that impact the answer to (1)?

**Comment by monkeyiq** [comment]
The default settings in `includes/ConfigDefaults.php` enable terasender. With this configuration an upload is performed by sending "chunks" of files in PUT requests. This is serviced by `classes/rest/endpoints/RestEndpointFile.class.php` in the `put` method. The put method accesses the uploaded file data directly from the request object.

There is a legacy method to upload a whole file in a single POST and that would be serviced by the `post` method in the same RestEndpointFile which then uses `$_FILES` and so upload_tmp_dir would come into play there. The biggest consideration would be to be able to quickly move a file from upload_tmp_dir to what `storage_filesystem_path` is set to in your config.php. For example making them both on the same filesystem.

A quick look at the php 7.3 sources shows that `upload_tmp_dir` is used in the POST upload (SAPI_POST_READER_FUNC & rfc1867.c).

So I think on a modern FileSender setup it shouldn't matter how you have set `upload_tmp_dir`.

There is another temp like setting, `tmp_path` which is used by the server side archive code to calculate how large the generated archive will be. This is needed to allow a download progress in the browser. That setting defaults to FILESENDER_BASE/tmp. Note that whole archive sized files are not written to tmp_path, only smaller stub files are created in order to work out the exact byte size of the archive metadata on disk.

I will update the various files and docs shortly. If anyone running a site has specific settings for anything that is counter to what I've said here please drop a line.

**Comment by monkeyiq** [comment]
The docs/v2.0/install/index.md already makes mention of a tmp directory which is at the default location that tmp_path will be looking. So again, if nothing is explicitly changed that should be setup already too.

**Comment by monkeyiq** [comment]
If the above PR https://github.com/filesender/filesender/pull/1350 leaves things still to do please reopen the issue.
