### ISSUE TITLE
PHP Fatal error in report_plain.php

### ISSUE THREAD

**Issue by liedekef** [filesender/filesender#1329]
This is sometimes reported in the logs (version 2.36):

[user.err] php: PHP Fatal error:  Uncaught Error: Call to undefined method stdClass::is() in /opt/filesender/templates/report_plain.php:15

the line in question:
`    if($entry->author_type == 'Guest' && $entry->author->is($entry->target->owner))`

This line is also present for report_pdf.php and report_html.php

**Comment by monkeyiq** [comment]
This was interesting to track down, assuming legitimate system use.  It turns out the auditlog/report code would smooth over an issue loading by returning a partial proxy object. That proxy object does not have a `is` method which is what can make the `stdClass::is()` call to signal an exception. In https://github.com/filesender/filesender/pull/1349 the proxy now includes a bogus object id which can be used to detect this situation and not call `is` and this not trigger an exception.

**Comment by monkeyiq** [comment]
Please reopen the issue if it is still present for you. Thank you for reporting this!
