### ISSUE TITLE
high cpu load

### ISSUE THREAD

**Issue by liedekef** [filesender/filesender#1409]
Hi, using the latest filesender on ubuntu 20.04, using nginx 1.18 (from Ubuntu repo), we frequently see high cpu load:

   1259 www-data  20   0   84592   8456   5256 R  **66.2**   0.1  14941:29 nginx                                                                                  
   1257 www-data  20   0   84220   8024   5216 R  **64.2**   0.0   1345:06 nginx                                                                                  
   1260 www-data  20   0   84632   8260   5076 R  **52.3**   0.0   3983:00 nginx                                                                                  
   1258 www-data  20   0   84800   8500   5196 S  **49.7**   0.1   7939:25 nginx                                                                                  

The load is not coming from php, but really from nginx. Is there any tuning recommendation to be done?
Our current nginx settings related to possible performance are:

```
    client_body_buffer_size 256k;
    client_max_body_size 32m;
    #client_header_buffer_size 1k;
    #large_client_header_buffers 2 1k;
    client_body_timeout 12;
    client_header_timeout 12;
    keepalive_timeout 15;
    send_timeout 10;
```
And the php fpm settings:
```
    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info         ^(.+\.php)(/.+)$;
        fastcgi_pass                    unix:/var/run/php/php7.4-fpm.sock;
        include                         fastcgi_params;
        fastcgi_intercept_errors        on;
        fastcgi_param PATH_INFO         $fastcgi_path_info;
        fastcgi_param SCRIPT_FILENAME   $document_root$fastcgi_script_name;
        limit_rate_after 900m;
        limit_rate      30m;
    }
```

So I'm open to suggestions :-)

**Comment by WebSpider** [comment]
In my experience, this could in general be a few things:

- Large chunk settings causing high mem utilization leading to swapping
- Storage not keeping up with the concurrency causing iowait
- Clients doing many restarts
- Chunking being disabled

**Comment by liedekef** [comment]
Chunk settings:

$config['download_chunk_size'] = 50 * 1024 * 1024; // 50MB
// never change upload_chunk_size or upload_crypted_chunk_size ...
$config['upload_chunk_size'] = 5 * 1024 * 1024;

vp.swappiness of the server is set to 10. While it does do some swapping, it is more opportunistic swapping (server has 16GB ram) because most of the mem  is being reserved in cache/buffers (so still free to be used).
Should I even lower swappiness? What is the recommended value for a vm running filesender here? In fact, some global performance guidelines for filesender would be handy (as in: use this much mem per client for nginx, use this value for swappiness ...), unless that already exists?
I'll check on the iostat of the disks (using ceph for the data disks, but it seems the root disk is mostly used because of nginx logging ... busy server :-) )
I've also seen this param now:
$config['storage_type'] = 'filesystem'; 
==> should that be changed to something else for ceph-storage (currently ceph volumes are being mounted as lvm disks)?

**Comment by monkeyiq** [comment]
It might be interesting to try to see where the full file scans are happening when not using chunked storage..

**Comment by monkeyiq** [comment]
IIRC some of the object store backings used to do hashes on written content. This could become very expensive for a FileSender upload because every time FileSender appends a new chunk to a file in `$config['storage_type'] = 'filesystem';` mode the backing object store recalculates it's hash value for that object. This may not be the case here as you would expect those cpu cycles to be shown for the object store rather than nginx.

If you have a chance to test with filesystemChunked that would rule out this possibility. You will need to make sure the upload and download chunk size is the same for filesystemChunked as it expects to read/write the same size chunked files. FileSender should mention this if you try changing over: https://github.com/filesender/filesender/blob/63ff441e94590fc3d9cc7b05cd0055a7b2c590f0/classes/utils/Config.class.php#L239

The actual storage class used for a transfer is stored per transfer, so you should be able to set the following and still download existing files. Though I haven't checked that in a while so a test would be prudent.

```
$config['download_chunk_size'] = 5 * 1024 * 1024; 
$config['upload_chunk_size'] = 5 * 1024 * 1024;
$config['storage_type'] = 'filesystem';
```

**Comment by liedekef** [comment]
Currently I have this for terasender config:
```
$config['terasender_enabled'] = true;
$config['terasender_worker_count'] = 6;
$config['terasender_start_mode'] = 'single';
$config['terasender_advanced'] = false;
$config['terasender_worker_xhr_timeout'] = 3600000;
```

Not sure what to do with terasender_start_mode though (in test I have it in "multiple" but I need to check what this actually does)

**Comment by meijer** [comment]
@liedekef is this still an issue or did you manage to find a solution?

**Comment by meijer** [comment]
No worries, then I'll close the ticket so it's not in the way of others.
