### ISSUE TITLE
Slow upload speeds

### ISSUE THREAD

**Issue by thuso607** [filesender/filesender#1454]
We are running a FileSender version 3.0 instance. A number of users have been complaining about slow upload speeds when using the application.

Is there a way we can improve the upload speeds of Filesender besides the use of the Terasender module that is already enabled. Which other components can I tweak to improve the upload speeds?

The configuration in filesender-php.ini
max_input_time = 3600
upload_max_filesize = 2047M
post_max_size = 2146445312 ; 2047M + 10K

**Comment by monkeyiq** [comment]
What sort of speeds are you able to achieve on your local network? You should expect to see well over 100mbyte/sec for encrypted and maybe twice that for non encrypted upload.

**Comment by thuso607** [comment]
I only get 3 Mbits/s on my local network for unencrypted upload. The uploads usually transfer the first 50MB fast then hangs afterwards. See below, the attached upload of a 1.5 GB file
![slowfilesenderupload](https://user-images.githubusercontent.com/22442842/234790596-99e4ff48-2937-4845-8278-99105ccafab9.PNG)

**Comment by monkeyiq** [comment]
It is useful that the performance can be tested locally.  Some options from my `/opt/filesender/config/config.php` which might improve performance. I have some digging into the worker_count to do at some stage as increasing that too much (12+ IIRC) started to work against performance here. Though not to the level you are getting.

```
$config['storage_type'] = 'filesystemChunked';
$config['terasender_worker_count'] = 4;
$config['encryption_key_version_new_files'] = 3;
```

Another option would be to increase the logging a little bit and see if chunks are resent. 

I will pull the latest 3.x release and do some more testing to revalidate my performance a little and try to lower it in order to discover options which might need attention.

**Comment by monkeyiq** [comment]
Using 3.x development, going from 4 to 12 in terasender_worker_count increases performance slightly (170 -> 180mb/s).

**Comment by monkeyiq** [comment]
Keeping the worker count at 12 and going to filesystemChunked moved to 184mb/s.

**Comment by monkeyiq** [comment]
Using log_facilities to syslog or error_log slows things down but only < 10%.

**Comment by monkeyiq** [comment]
FWIW I am testing on apache
```
php-fpm-8.1.17-1.fc36.x86_64
httpd-2.4.56-1.fc36.x86_64
```

**Comment by monkeyiq** [comment]
The storage partition I am using is backed here by a SATA SSD. Which will probably limit things to <500mb/s.

**Comment by monkeyiq** [comment]
At this stage I am not sure that the filesender config.php will contain something that will slow things down for me to the level that you are experiencing :/

**Comment by monkeyiq** [comment]
Do things perform as badly on an empty database? Which OS, web server, db are you using?

**Comment by monkeyiq** [comment]
I am guessing that Centos and fc36 are close enough. The apache versions are very similar too.

Is it possible to spin up a VM to run a test instance and see if that has the same performance issues? If the new test instance is slow as well at least then we could assume the database is not slowing things down and if it is fast in the new VM we have two data points to try to converge to find the issue?

**Comment by thuso607** [comment]
Good day,

The transfer upload speeds fluctuate. Sometimes the uploads are faster and sometimes slower. I tried uploading a 3GB file and I get terasender error. see attached image
![terasender error](https://github.com/filesender/filesender/assets/22442842/e7bcf603-aec7-4b02-a91e-86415595c18b)

**Comment by monkeyiq** [comment]
I have created a branch in my fork with some more debug https://github.com/monkeyiq/filesender/tree/2023/may/slow-upload

This assumes a test instance that is apart from the main working one so that options can be available which would otherwise cause the system to not work as expected. More on this below.

I made the javascript messages have AAA, BBB, and CCC in them so they can easily be found in the web console. 

I also added a testing option to the filesystem storage to just report that data is written but not actually write the data. With this option in my config.php I go from about 180 mbyte/s to 210 mbyte/s. The upload will not complete properly with this option set, but during the upload you should get an idea of the overall speed. This might help isolate if the writing to disk is the problem.

```
$config['storage_type'] = 'filesystem';
$config['TESTING_do_not_write_data'] = true;
```


Are the requests going directly to apache or via a proxy/balancer first?
I assume there is nothing about the 408 in `/opt/filesender/log`

**Comment by thuso607** [comment]
How do I tell if the disk writing is the issue, what will be the resulting output to check out in the logs? 

The requests are going directly to Apache. Correct, there is nothing about 408 in the log files.

**Comment by monkeyiq** [comment]
I don't think the FileSender logs do anything special for slow writes at the moment. You could use the above branch which allows for no actual writes, or look into iotop, vmstat, blktrace, etc or use an alternate storage location.

**Comment by thuso607** [comment]
The issue happens intermittently and when I restart httpd it starts uploading normally.

**Comment by thuso607** [comment]
What causes the progress of an upload to go back and retransmit packets. See the attached screen grab video. The upload was at 97% then it went back to 80%. Any information on what could be causing this will be appreciated.
https://github.com/filesender/filesender/assets/22442842/f236049e-0580-4e36-924f-39314c215911

**Comment by WebSpider** [comment]
This is when a chunk upload failed, and FileSender is retrying the chunk.
