### ISSUE TITLE
UI3: Code details - Language of transfer during upload

### ISSUE THREAD

**Issue by WebSpider** [filesender/filesender#1620]
(code33) upload: functionality reduction, can not select the language for the transfer

**Comment by monkeyiq** [comment]
I always thought this was a cool feature. If you knew that you were sending a file to somebody who preferred a human language you could select that in the upload to make their email notifications etc in that language.

**Comment by monkeyiq** [comment]
I have also looked at how to make that sticky so that the links in the emails select the language as well. I have left that out for now as the user's browser should be telling FileSender what their preference is. 

The language selection for a transfer box is useful for the email system where there is no such knowledge so that a user in one country can opt to select the language of another if they are sending a file to a colleague in that country.
