### ISSUE TITLE
Attribute requirements for Filesender

### ISSUE THREAD

**Issue by surfnet-niels** [filesender/filesender#1781]
The install docs (https://docs.filesender.org/filesender/v2.0/install/) talk about the IdP attribute requirements and point to https://docs.filesender.org/filesender/v2.0/admin/reference/#idp_attributes. However that page does not have a section on IdP requirements.

**Comment by monkeyiq** [comment]
Thanks for the report. I will update the docs soon now that I have more of an understanding of IdP attributes.

**Comment by monkeyiq** [comment]
Before I get the docs update... the AuthSPSaml.class.php file processes the attributes. It looks for uid, name, and email. The uid and email must be present. The name will be taken from the email if it is not present. 

These uid, name, and email are found using the filesender config.php settings `auth_sp_saml_email_attribute` https://docs.filesender.org/filesender/v2.0/admin/configuration/#auth_sp_saml_email_attribute and the like. So by default email is taken from the SAML attribute mail, name from the SAML cn, and the uid from the SAML eduPersonTargetedId. The filesender config.php settings let you change what SAML attribute to inspect (or a list of them) to obtain these values.

In a default FileSender install the SAML attributes `eduPersonTargetedId` and `mail` are required to login.


The `auth_sp_additional_attributes` config.php setting can be used to allow access to other SAML attributes as well.

**Comment by monkeyiq** [comment]
If the above makes sense I will use that as the core of a docs update

**Comment by monkeyiq** [comment]
I have merged the above information into the reference docs.
https://github.com/filesender/filesender/pull/1795

**Comment by monkeyiq** [comment]
Please reopen the issue or submit new ones if find the docs lacking. Thank you.

**Comment by peter-** [comment]
> So by default email is taken from the SAML attribute mail, name from the SAML cn, and the uid from the SAML eduPersonTargetedId. The filesender config.php settings let you change what SAML attribute to inspect (or a list of them) to obtain these values.
> 
> In a default FileSender install the SAML attributes `eduPersonTargetedId` and `mail` are required to login.

Note that the [eduPersonTargetedID attribute has finally been deprecated 4 years ago](https://wiki.refeds.org/display/STAN/eduPerson+2020-01#eduPerson202001-ChangeLog) in the relevant specification. As such that makes for a bad default because it really should be avoided for any new services/deployment (with `pairwise-id` from the [SAML 2.0 SubjectID Attributes Profile](https://wiki.oasis-open.org/security/SAMLSubjectIDAttr) being the most direct replacement).

Most people will change that config value anyway but *defaulting* to an attribute that according to the spec's author was made obsolete in 2005 CE when SAML 2.0 was released and now was deprecated in the eduPerson specification in 2020 CE gives that attribute more prominence and visibility than it deserves in 2024 CE.

**Comment by WebSpider** [comment]
Thanks @peter- for chiming in. This is why having a community is great, as most of the people involved in FileSender development really are not involved in all areas.

Do you have a suggestion what we should change this default to, maybe even a PR? :)

**Comment by monkeyiq** [comment]
@peter- Thank you for the comment! I have created https://github.com/filesender/filesender/pull/1822 which I think captures the more modern configuration. Reading about the pairwise-id in the spec was informative.

I have limited the scope of changes in 1822 to just eduPersonTargetedId though there may be other items in FileSender which are still using deprecated SAML attributes. Always easy to make more PRs to modernize things.
