### ISSUE TITLE
auth_remote_too_late errors not returning HTML

### ISSUE THREAD

**Issue by multimeric** [filesender/filesender#1806]
I'm working with a FileSender server that has recently updated to version 2.45. I noticed that the `auth_remote_too_late` errors are no longer being returned as JSON. So for example when I `PUT https://filesender.aarnet.edu.au/rest.php/file/21792367/chunk/629145600`, I now get an HTML page containing:
 
```html
<div class="exception">
    The application encountered an error while processing your request

    <div class="message">
        <h1>Service Unavailable</h1>
        <p>FileSender is temporarily unavailable, please check back soon.</p>
        <p>For more information, please <a href=mailto:support@aarnet.edu.au</a>contact us</a></p>
    </div>
</div>
 ```

Admittedly I'm not sending an `Accept: application/json`. Did this change recently?

**Comment by PaulLocksley** [comment]
I don't think this is actually due to Filesender, I did some testing with 2.47 and I am still getting :
`Fail Reason: 500
{"message":"auth_remote_too_late","uid":"6610ea60a59a4","details":null}`

Looking at the realease notes I don't believe this was fixed elsewhere but happy to be corrected. 
I would guess this is due to the FileSender/infra configuration.

**Comment by WebSpider** [comment]
It would seem there is a custom error page in play here

**Comment by multimeric** [comment]
Thanks! I'll follow up with the hosts of my FileServer instance.

**Comment by madsi1m** [comment]
Can confirm this is due to a local config on our end. A change has been deployed in our systems.
