### ISSUE TITLE
Filesender version 2.49 failing to upload files issue

### ISSUE THREAD

**Issue by thuso607** [filesender/filesender#1987]
I just installed version 2.49. I am testing file uploads and the files fail to upload. No chunks are getting written to the storage filesystem. Please assist what could be the issue. The logs are not showing any chunks being written. I tried this on different file sizes and I am not able to upload with any file size. I also get a gui translation warning "No translation found for statevent_upload_maxsize_ended in en-us language". See attached screenshots.

![image](https://github.com/user-attachments/assets/4531b4c4-2922-4377-99b5-c179828fc477)

![image](https://github.com/user-attachments/assets/a115f78d-30fb-4ed5-bcf4-be4da3745066)

![image](https://github.com/user-attachments/assets/bbaafd16-ea9c-4d8c-994d-754e51c3a9b1)

**Comment by monkeyiq** [comment]
I think the translation messages will not be stopping the upload from happening. So, handy to investigate after we resolve the core issue.

If no chunks are being written... I assume the simple things like file permissions, free space etc have been tested for. 


Take a look at the DevTools (Control+Shift+I in Chrome). Specifically at the network tab. You should see...

A POST to https://myhost/filesender/rest.php/transfer 
which contains json data including information on the files you have selected.

... other requests that are not interesting for js files et al ...

A PUT to upload the first chunk
https://myhost/filesender/rest.php/file/1234/chunk/0?key=aa4...
where 1234 is the file number for this new upload.

That should also have things like X-Filesender-File-Size: in the request telling the FileSender server the byte size of this first file.

That PUT has a status code of 200 for me here.

After all chunks are uploaded there is a confirmation that is used but I suspect you do not get there.

If we know which if the network requests is failing we can start to hone in on why. Adding more debugging calls on the server until we find out why.




This is part of my config.php file, I try a number of `storage_type` settings as I expect users will be using many of them.
```
$config['storage_type'] = 'filesystem';
//$config['storage_type'] = 'filesystemChunked';
```

From part of my /opt/filesender/log/file
```
[rest:info] Event#transfer_started on Transfer#2059
[rest:info] [user 38] [rest:info] Event#transfer_started on Transfer#2059
[rest:info] Transfer#2059 started
[rest:info] [user 38] [rest:info] Transfer#2059 started
...some debug messages for translations...
...sql for UPDATE Transfers SET...
[rest:debug] /opt/filesender/www/rest.php:37 RestServer::process() Got data to send back
```

**Comment by thuso607** [comment]
Hi,

This is the error I am getting under DevTools. See attached.
![image](https://github.com/user-attachments/assets/462731f7-7aa8-4043-8478-2a15a2a2d86a)

**Comment by monkeyiq** [comment]
So something is failing between the line

https://github.com/filesender/filesender/blob/59f021fa7dc5c87bc25301a7b3ecce3cf2044d2d/www/js/transfer.js#L1212

and

https://github.com/filesender/filesender/blob/59f021fa7dc5c87bc25301a7b3ecce3cf2044d2d/www/js/transfer.js#L1253

The main call done between them is to `RestEndpointTransfer.class.php::post`. I assume you will get to this line in that method
https://github.com/filesender/filesender/blob/59f021fa7dc5c87bc25301a7b3ecce3cf2044d2d/classes/rest/endpoints/RestEndpointTransfer.class.php#L517

You might like to add some general print type calls from there down to try to work out where things are failing?
```
Logger::error("DEBUG 1");
```

**Comment by l0bzt3r** [comment]
I experienced a similar issue on debian12 bookworm (php 8.2).
it worked fine with FileSender 2.47.
After upgrading to both 2.48 and 2.49 the issue appeared. Uploading files appeared "stuck" to the user and the admin page did not list previous uploads.
### Debugging
In order to debug the issue I've set the following values in  /etc/php/8.2/apache2/conf.d/filesender-php.ini:
`; To turn on logging to syslog uncomment the following lines:`
`log_errors = on`
`error_log = syslog
`
After setting these values the following error appeared in syslog when the upload problem occurred:
`simplesamlphp[1414]: PHP Fatal error:  Uncaught Error: Class "IntlGregorianCalendar" not found in /opt/filesender-2.20/filesender-2.48/lib/vendor/php81_bc/strftime/src/php-8.1-strftime.php:93`
`simplesamlphp[1414]: Stack trace:`
`simplesamlphp[1414]: #0 /opt/filesender-2.20/filesender-2.48/lib/vendor/php81_bc/strftime/src/php-8.1-strftime.php(199): PHP81_BC\{closure}()`
`simplesamlphp[1414]: #1 [internal function]: PHP81_BC\{closure}()`
`simplesamlphp[1414]: #2 /opt/filesender-2.20/filesender-2.48/lib/vendor/php81_bc/strftime/src/php-8.1-strftime.php(180): preg_replace_callback()`
`simplesamlphp[1414]: #3 /opt/filesender-2.20/filesender-2.48/classes/utils/Utilities.class.php(195): PHP81_BC\strftime()`
`simplesamlphp[1414]: #4 /opt/filesender-2.20/filesender-2.48/classes/rest/RestUtilities.class.php(137): Utilities::formatDate()`
`simplesamlphp[1414]: #5 /opt/filesender-2.20/filesender-2.48/classes/rest/endpoints/RestEndpointTransfer.class.php(71): RestUtilities::formatDate()`
`simplesamlphp[1414]: #6 /opt/filesender-2.20/filesender-2.48/classes/rest/endpoints/RestEndpointTransfer.class.php(865): RestEndpointTransfer::cast()`
`simplesamlphp[1414]: #7 /opt/filesender-2.20/filesender-2.48/classes/rest/RestServer.class.php(302): RestEndpointTransfer->post()`
`simplesamlphp[1414]: #8 /opt/filesender-2.20/filesender-2.48/www/rest.php(37): RestServer::process()`
`simplesamlphp[1414]: #9 {main}`
`simplesamlphp[1414]:   thrown in /opt/filesender-2.20/filesender-2.48/lib/vendor/php81_bc/strftime/src/php-8.1-strftime.php on line 93
`
### Resolution
I was able to resolve the issue by installing the vendor packages php-date and php-intl (I'm not sure whether php-intl is actually needed).

**Comment by WebSpider** [comment]
I can confirm php-intl is needed in recent versions of filesender-2
