### ISSUE TITLE
Creating Guest Voucher doesn't mail it out to recipient.

### ISSUE THREAD

**Issue by sndrsmnk** [filesender/filesender#29]
Creating a Guest Voucher for an email address doesn't immediately email that voucher to the address provided, unlike the message that appears after clicking Submit would indicate.

The voucher does get mailed to the recipient when the 'Send Reminder'-button is used.

PHP7.0, git master.

**Comment by madsi1m** [comment]
Hi, I had a problem like this where the guest email never sends.
I commented out this line from classes/data/Guest.class.php
if($this->getOption(GuestOptions::EMAIL_GUEST_CREATED))

The idea is that it always runs the next line which does the quickSend()

**Comment by sndrsmnk** [comment]
Thanks for that tip. I hadn't looked into it yet.
Still a bug though :-)

**Comment by Veredior** [comment]
Hi, it does work, just check in your config file in the ``$config['guest_options']`` param for this  : 
``// Notify the recipient when created a guest voucher
	'email_guest_created' => array(
		'available' => true,
		'advanced' => true,
		'default'  => true
	),``
It seems that this option is disabled by default...

**Comment by sndrsmnk** [comment]
I'm quite new to FileSender, so forgive my bluntness but the `available` flag seems to only show/hide the toggle on the webinterface? It isn't entirely clear what the meaning of 'available' is.

Also, the `default` value for `email_guest_created` in `includes/ConfigDefaults.php` is `true`. I would expect it to be the default then, even though the option to switch it off in the webinterface is not `available`.

And also if my understanding of the `available` flag is wrong, i think this is a bug. ;)

The interface states a message is sent while it is not and there's no way to manually figure out the Voucher link though the webinterface.

**Comment by Veredior** [comment]
Agree, some parameters don't have an impact on the UI which likely cause confusion. I will make a PR to fix this issue as this parameter should be enable by default...

**Comment by madsi1m** [comment]
I will uncomment it in my install as well. Good find, should be on by default

**Comment by jornane** [comment]
Seems like there is some confusion here. According to [guest_options](http://docs.filesender.org/v2.0/admin/configuration/#guestoptions), the **sender** of a voucher should get a mail when `email_guest_created` is set, and the **recipient** of a voucher should get a mail when `email_guest_created_receipt` is set.

It seems like the comment in the example config file (as referred to by @Veredior ) has a comment indicating the opposite. I think that the correct fix is to make the options reflect their documented behaviour, where the link I sent earlier is the authoritative copy. Any other documentation (such as comments) should be brought up to date with this.

**Comment by jornane** [comment]
It looks like I was wrong by trusting the documentation. I get the strong impression that the explanations for `email_guest_created` and `email_guest_created_receipt` have been switched around.

@sndrsmnk asked about the meaning of `available`. Prior to #34, it hides the option in the webinterface, and forces the value to `false`, regardless of the `default` value. This is indeed a bug, it should hide the option in the webinterface and force the value to the `default` value. #34 fixes this.

However, the documentation should still be fixed.

**Comment by jornane** [comment]
Documentation is updated.

**Comment by monkeyiq** [comment]
There were some pull requests aimed at solving similar issues. I have merged https://github.com/filesender/filesender/pull/33 and closed https://github.com/filesender/filesender/pull/32. The solution in 33 used html for attributes to associate elements so that the javascript wasn't needed. The code in 32 updated the javascript to handle things better.

The code in https://github.com/filesender/filesender/pull/34 as mentioned a few comments above returns default values when they are not explicitly found. This should allow things like email settings to have the default value instead of false when the user has not seen or interacted with the UI (which might be hidden etc). On the other hand https://github.com/filesender/filesender/pull/31 seems more targeted at showing the option to the user (who may not even care to see it).

I'll have a dig around shortly to verify guest creation and voucher email out and check that the process works as one might expect.

**Comment by monkeyiq** [comment]
I have now tested with guests with "get a link" selected and not selected. For me the guest invitation is sent right away to the guest now.
