### ISSUE TITLE
timezones

### ISSUE THREAD

**Issue by madsi1m** [filesender/filesender#354]
Hi, our filesender deployment is used by people in different timezones. Our servers are set to UTC. Is it possible for filesender to use the clients timezone (pull it from $_SERVER or javascript) and have it converted to servers timezone when storing in db?

This will reduce some confusion our users are having.

**Comment by monkeyiq** [comment]
I think it might become more confusing if the time used for transfers and files on the server is local to any one client machine. That transfer will be less confusing for a user uploading in Brisbane, but more confusing for somebody in LA. Unless the server knows the first user is in Brisbane and can do a double adjustment to show localtime to the LA user.

On the other hand if the server keeps storing timezones in UTC it is a little simpler to convert to the user local timezone for display. It might be a good idea to add a uesr timezone offset to UserPreferences so emails can be adjusted to the users default tz where there is no browser to give away that data.

It seems the my transfers and file download only show the date. On the other hand the see transfer log does show me native UTC instead of localtime on my local server which is less than optimal for most.

**Comment by madsi1m** [comment]
If emails and display are in local time and everything on the db is UTC this might make things easy

**Comment by madsi1m** [comment]
Hi this has come up again recently.
As our servers are in UTC and most of our local time is AEDT, users are saying that transfers appear to expire a day early when in fact they are expiring at the correct UTC time.

Perhaps we can add an editable user timezone or timezone offset to UserPreferences and adjust the display times like that?

**Comment by monkeyiq** [comment]
I am working on an update for this issue. I will probably add both the use of a js set option and a default in the database. 

The first option is handy for travel, if you move between time zones having the server show you relative to where you are might be nice. But it is also a bit of a privacy intrusion so will be a configurable option in config.php.

The second is obviously data that the user has explicitly sent... Or probably for you the default db value being AEDT and users in Perth, brissie, et al. setting their timezone more explicitly.
