### ISSUE TITLE
use libsodium.js for "everything crypto"

### ISSUE THREAD

**Issue by fkooman** [filesender/filesender#377]
Here a full example of everything you need in Filesender:

* generate a password
* derive a key from the password
* (stream) encrypt the file blocks
* (stream) decrypt the file blocks

https://gist.github.com/fkooman/22a54668f0db7cf167a1d04e9dddc8c3

**Comment by vanrein** [comment]
I also believe that [AEAD](https://download.libsodium.org/doc/secret-key_cryptography/aead) adds value, but otherwise your list looks complete.

**Comment by vanrein** [comment]
After comparing your back-and-forth communication I also **strongly urge** the immediate move towards libsodium and completely getting rid of the WebCrypto API.  Thanks for bringing that up, François, along with your many other good points.

When I wrote the report, WebCrypto API was just released and a *fait accompli*.  And it shows -- I had to trick around with the IV, consisting of 96 bit random material and 32 bit block number and explicit attention to the last block.  Nice that this turned out to all be possible, but it's been quite a stretch to implement the things that should be in a reasonable crypto API.

A very good crypto-aware programmer can do secure things with WebCrypto API, I believe, but libsodium makes secure programming accessible to many more.  The fact alone that API specs are not always completely clear -- KeyImport, does it read binary data or other? does it take out all entropy, or does it cut off when it had enough?  These things should be clear because otherwise you are missing out on entropy -- and on security.

**Comment by fkooman** [comment]
> I also believe that AEAD adds value, but otherwise your list looks complete.

Honestly, I didn't look that far. libsodium has a construct explicitly for "streams" (https://download.libsodium.org/doc/secret-key_cryptography/secretstream) which seemed appropriate here when you try to encrypt/decrypt (huge) streams of data through the "HTML5" File API. But I'm no crypto expert, that's why I use libsodium ;)

Also: https://blog.cryptographyengineering.com/2012/12/28/the-anatomy-of-bad-idea/

**Comment by vanrein** [comment]
We had a discussion today, and now aim for libsodium; assuming the FS board will go along.  The reasons are as stated above.

Another point where your example is too limited for FS is that it cannot encrypt blocks concurrently.  This is why we setup for AES-GCM.  I will look into ChaCha and Poly, don't know if they can offer the same degree of protection.

I'll modify your example then, so Ben has some concrete code to work into the complexities of FS that he knows best.  One remark he made is that the knowledge about how to do things is currently a bit spread over the document, and a simple code example can remedy that.

**Comment by fkooman** [comment]
> too limited for FS is that it cannot encrypt blocks concurrently

Is this currently supported in FS and results in a substantial increase of performance? Even with xchacha20poly1305? I'd be _very_ careful dropping the built-in protection that you get for free with the libsodium stream crypto API, *designed* for stream data & files! Keep it simple!

> a simple code example can remedy that

You did find https://gist.github.com/fkooman/22a54668f0db7cf167a1d04e9dddc8c3, so I'm not sure I understand...

**Comment by vanrein** [comment]
Yes, it is currently supported AFAIK.  I have not question it, as I am only reviewing the cryptography.  I also don't know if these numbers improve or flatten out with HTTP 2.0 and/or request pipelining.

You've succeeded at breaking through the initial pre-set notion of WebCrypto API, if you want to challenge this one too then I suggest you talk to Rogier.  My opinion does not matter, but in general I also like code as if it gets simpler (and we're the only ones on this issue, it seems).

**Comment by fkooman** [comment]
> Yes, it is currently supported AFAIK. I have not questioned it, as I am only reviewing the cryptography. I also don't know if these numbers improve or flatten out with HTTP 2.0 and/or request pipelining.

I'd say those questions need to be answered first. Without actually doing that work, I'd recommend using the simple proposed "streaming" API as mentioned above.

> My opinion does not matter

Neither does mine, and I am not patient enough, nor do I have the energy, to try to keep and change a project where the priorities are fundamentally different.

**Comment by monkeyiq** [comment]
it would seem that perhaps something other than libsodium is now the desired target.
