### ISSUE TITLE
Right menu does not appear

### ISSUE THREAD

**Issue by Veredior** [filesender/filesender#431]
With the addition of the new pages in the menu like Profil and Privacy, the menu which is 800px long is too short to show the class `rightmenu`.

![ui 800px long](https://user-images.githubusercontent.com/5888795/45756475-3ab9d500-bc21-11e8-9a57-ab1ec008fdc4.png)

By changing the length for `#wrap` to 1000px it does appear.

![ui 1000px long](https://user-images.githubusercontent.com/5888795/45756503-51602c00-bc21-11e8-92f5-e80bf78c1fe4.png)

I think the issue appears when the translation of the menu terms are too long.

For example in french "Privacy" => "Confidentialité", which at 800px hides the disconnect button.

I think using a new system for the menu like a dropdown may solve this issue.

Generally, depending of the language, the 800px length is a bit too short, for the differents tables used in the admin and the list of transfers.

**Comment by peter-** [comment]
Same here with the German translation which is rather literal and verbose (`My transfers` becoming `Meine Übertragungen`, etc.) and therefore the text is running wide. Not sure yet I'll change the CSS or rather try to find simpler wording for the menu entries, i.e., provide a different translation locally.

The problem is slightly worse for admins (who shouldn't actually need anything from the right menu, as switching language or logging off is also possible simply by URL hacking, and admins shouldn't need the `Help`, `About` and `Privacy` links) due to the extra menu entry. The new (or newly shown by default) profile menu entry also takes up extra space.

In general the menu layout could use some improvements. Maybe unifying `My profile`, the language switcher and `Log-off` into one dropdown menu would save sufficient space. Also, `Help`, `About` and `Privacy` are all a bit similar and all generic (i.e., not related/specific to the subject), so maybe those could be unified on a single page or into a dropdown menu as well.

**Comment by OK1FWG** [comment]
And I wondered where is my Log-out button after switching to other language :-)

**Comment by monkeyiq** [comment]
I have created https://github.com/filesender/filesender/issues/477 to make the language selector work when there is no existing lang setting and enable that feature by default. The setting is stored in the database already per user. It is a shame that this is not more widely enjoyed.

Perhaps rather than having the language selector in the top menu a better choice might be to move folks to a welcome screen when they first login or to the my profile so people can select the language they are most comfortable with.

**Comment by monkeyiq** [comment]
I had been thinking about moving help, about, privacy into a "hamburger menu" but that also relies on the user being familiar with that &#8801; style icon and what it might mean.

Other options I am considering are merging about and help into a single page, and adding a link to the privacy page from my profile and removing it from the top level menu by default.

**Comment by monkeyiq** [comment]
There are some things in motion for a GUI update https://sympa.uninett.no/lists/filesender.org/arc/filesender-dev/2019-03/msg00001.html. I don't know about the time frame for those but it does lead me to think more about putting in place options to help the current menu issues rather than trying to create drop down menus or other things only to have those removed some time soon.

I have made the user profile page have a link to privacy information so the privacy menu item is now not the only way to get to that information https://github.com/filesender/filesender/pull/482

In order for the language selector (if enabled in the menu bar) to not disappear I have also got a PR in CI stage that moves the selector to above the main menu https://github.com/filesender/filesender/pull/484. I would have liked to move it to the very top right as that seems a common design but the header image has the curved corners as part of the image which would then require two images (lang selector on/off) and a more complex update.

A possible solution for the left side menu is to move the "admin" to a link on the my profile page. This may or may not annoy admins as they would have two clicks or a bookmarking to get direct access. This part is likely less of an issue as @peter- mentions because if you are an admin you are likely not so interested in the items on the right side. Perhaps if the logoff can be forced to always be available there it would be nice.

I am testing at 800px with many languages and the drop down lang selector enabled.

**Comment by monkeyiq** [comment]
The merging of https://github.com/filesender/filesender/pull/485 gives some breathing space with the menu again. That and moving the optional language selector out of the menubar itself and other changes listed above should mitigate this issue until we move to something more robust such as using bootstrap for menus and page layout.
