### ISSUE TITLE
Filesender: expiration date is not correct

### ISSUE THREAD

**Issue by ziemerink** [filesender/filesender#436]
If you upload a file 1-10 2018 then the system defines by default that you can download it until: 11/10/2018 however is in the mail as expiration date; 1-10 2018! We use the Dutch .

**Comment by OK1FWG** [comment]
I have the same issue since 2.3. I am using cs_CZ, also the expiration date was displayed as 21/11/R and had to change the string in translation file.
My config:
$config['max_transfer_days_valid'] = 7;
$config['default_transfer_days_valid'] = 5;

Correct expiry date is shown, but after transfer, expiry date is either the same day or max. 1 day later.

**Comment by pvelati** [comment]
Hello, I have the same problem. When I upload a file with some browser the expiration date is the date after the upload. And if I change the date with datepicker, I obtain "gg/02/aa" without changing it.

Linux (Debian 9):
Chrome 72: ERROR
Firefox 60.5: OK

Windows 10:
Chrome 72: ERROR
Firefox 65: ERROR
Edge: ERROR

Now I'm checking the code

**Comment by pvelati** [comment]
I've checked the code and the translation. I see that 
  110 => 
  array (
    'term' => 'dp_date_format',
    'definition' => 'dd/mm/yy',
    'context' => '',
  ),
must be set like that (the default value). if you change it, then there are problems with the datepicker.
(for the italian language, I had gg/mm/aa and it didn't work. Now with dd/mm/yy it works)

**Comment by monkeyiq** [comment]
The are a few translation strings that are used for dates here.
On the server side `date_format` is used, or maybe `datetime_format` if the time is also to be included. For these calendar things it will be date_format since the time of day is not included.

The default for `date_format` in english is d/m/Y. This format follows the information given on the php date page https://www.php.net/manual/en/function.date.php.

For the datepicker jquery item the `dp_date_format` is used. The default for `dp_date_format` for english is 
dd/mm/yy. The format follows the information for the jquery datepicker widget http://api.jqueryui.com/datepicker/#utility-formatDate.

To make the experience nice for the user these two formats need to present dates in a manner that each can understand. For complete niceness the dates should present to the user exact identical information.

The current Dutch translations have date_format="d/m/Y" and dp_date_format="dd-mm-yy". If I set these date formats in the English locale I see that the date picker shows me a date in about a week but when I finish the upload the expires is set to today. So it appears that the incompatible date formats used in the two situations is causing the original bug listed above.

**Comment by monkeyiq** [comment]
Looking at @OK1FWG situation,

The cs_CZ in filesender 2.3 has the date_format of `d/m/R` and dp_date_format of `dd/mm/rr`
https://github.com/filesender/filesender/blob/1653888cba3885f2af65913e9960eac0caf4dec6/language/cs_CZ/lang.php#L84
https://github.com/filesender/filesender/blob/1653888cba3885f2af65913e9960eac0caf4dec6/language/cs_CZ/lang.php#L109

If I set my formats to those then I see something like 30/3/R in the date picker on the upload page. Using the picker to select a valid date I then see 04/04/rr in the picker display. After sending the file I see 4/4/R in the expires place, so it seems to be using the current year and a quick sniff at the database confirms it. Though not seeing the year on the web interface is fairly dubious.

These two format strings are very likely misplaced in the translation portal. They offer at best a method to format the date slightly differently to be more inline with expectations for a locale. The formatting itself must be done with english characters however, such as dd/mm/yy instead of the R/r usage.

**Comment by monkeyiq** [comment]
Since this happens on poeditor I am putting my change list here too in case something unexpected happens. An example of datetime_format in use can be seen in the auditlogs button of my transfers. Unless things are different on other systems the "J" in datetime_format just appears as is for me. The "U" also presents seconds since epoch, which may well not be what the reader would expect in the hours column. I am hoping my updates are inline with expectations of date formatting in Dutch  https://en.wikipedia.org/wiki/Date_and_time_notation_in_the_Netherlands

Dutch translations

```
  old as of march 2019
    datetime_format = d/m/J U:m:s   (last edited 3 years ago)
    date_foramt = d/m/Y             (last edited 10 months ago)
    dp_date_format = dd-mm-yy       (last edited 3 years ago)

new
    $lang['date_format'] = 'd-m-Y';
    $lang['datetime_format'] = 'd-m-Y H:m:s';
    $lang['dp_date_format'] = 'dd-mm-yy';
```

**Comment by monkeyiq** [comment]
It seems the German translations are all matching up already
```
German as at march 2019
    date_format = d.m.Y 
 dp_date_format = dd.mm.yy 
datetime_format = d.m.Y H:i:s

```

**Comment by monkeyiq** [comment]
@pvelati I am not sure if gg/mm/aa is selecting day / month / year.  From my searching around gg should become the weekday like "sabato". It seems the datepicker jquery widget is very english focused when it comes to specifying the formatting http://api.jqueryui.com/datepicker/#utility-formatDate

It seems the month names and day names can be set for the locale but formatting using more specific details for a language is not so straightforward. I might do a little digging in that area if there are datepicker extensions to help allow it.

I am not sure if slashes are the preferred format or - as separators.
https://en.wikipedia.org/wiki/Date_and_time_notation_in_Italy

```
Italian  as at march 2019
    date_format = d/m/Y 
 dp_date_format = dd/mm/yy 
datetime_format = d/m/Y H:i:s 
```

**Comment by monkeyiq** [comment]
The above PR should allow the formats to be slightly different but still work.

**Comment by monkeyiq** [comment]
I am now in the process of reimporting the updated language translations including the newly formatted date_format strings. For example https://github.com/filesender/filesender/pull/504

**Comment by monkeyiq** [comment]
I have now reimported languages from poeditor. The new formatting string used with strftime brought in with https://github.com/filesender/filesender/pull/500 and the updated translation imports should allow better localization and also allow the dp_date_format and date_format to differ slightly without causing an issue.
