### ISSUE TITLE
Spurious whitespace chars in de_DE

### ISSUE THREAD

**Issue by peter-** [filesender/filesender#438]
PR #366 brought in "open box" blank symbols in the files [language/de_DE/accepttoc.html.php](https://github.com/filesender/filesender/blob/master/language/de_DE/accepttoc.html.php#L10) and [language/de_DE/report_pdf_disclamer.html.php](https://github.com/filesender/filesender/blob/master/language/de_DE/report_pdf_disclamer.html.php#L10).  
(To me that hints at some import script error, but who knows. As it is those two files could probably be removed completely.)

Removing those from the PHP code is useless since according to the comment headers those files are auto-generated from `https://poeditor.com` -- but I don't want to have to create Yet Another Account there only to fix this. (When trying to log in via Github poeditor.com wants _full read and write access_ to my "private email address" and "private profile", which I have no interest in providing, and singing up with an email address is blocked from certain addresses, e.g. mailinator.)

**Comment by monkeyiq** [comment]
For German on poeditor I am seeing report_pdf_disclamer as what appears to be a red U. While accepttoc is now "Ich akzeptiere die Bedingungen dieses Dienstes". I think maybe the former should be blank if not set. 

I suspect that report_pdf_disclamer got set to a space in order to have the translation stats show that everything is translated (100% for english). This is a catch of using the translation portal to contain optional strings such as these disclaimers.

**Comment by monkeyiq** [comment]
This should be fixed now and further imports will convert openbox to space.
