### ISSUE TITLE
uid Data too long for column

### ISSUE THREAD

**Issue by jiscfoo** [filesender/filesender#463]
When using FileSender (2.5) SimpleSAMLphp (1.16.3) with `eduPersonTargetedID` as a uid attribute, the MySQL database column isn't wide enough to hold the attribute. For me tt needs to be at least `varchar(307)` but is only a `varchar(170)`. Given that some EntityIDs are quite long, perhaps make this `varchar(512)`?

```
[gui:error] [DBIUsageException exception uid:5c503a026f41a] database_access_failure
[gui:error] [DBIUsageException trace uid:5c503a026f41a] #0 /opt/filesender/classes/data/DBObject.class.php(624): DBIStatement->__call('execute', Array)
[gui:error] [DBIUsageException trace uid:5c503a026f41a] #1 /opt/filesender/classes/data/DBObject.class.php(363): DBObject::insertRecord(Array)
[gui:error] [DBIUsageException trace uid:5c503a026f41a] #2 /opt/filesender/classes/data/Authentication.class.php(151): DBObject->save()
[gui:error] [DBIUsageException trace uid:5c503a026f41a] #3 /opt/filesender/classes/data/Authentication.class.php(164): Authentication::ensure('<saml:NameID xm...')
[gui:error] [DBIUsageException trace uid:5c503a026f41a] #4 /opt/filesender/classes/data/User.class.php(213): Authentication::ensureAuthIDFromAuthUID('<saml:NameID xm...')
[gui:error] [DBIUsageException trace uid:5c503a026f41a] #5 /opt/filesender/classes/auth/Auth.class.php(185): User::fromAttributes(Array)
[gui:error] [DBIUsageException trace uid:5c503a026f41a] #6 /opt/filesender/classes/auth/Auth.class.php(241): Auth::user_protected()
[gui:error] [DBIUsageException trace uid:5c503a026f41a] #7 /opt/filesender/classes/auth/Auth.class.php(287): Auth::user()
[gui:error] [DBIUsageException trace uid:5c503a026f41a] #8 /opt/filesender/www/index.php(39): Auth::isAuthenticated()
[gui:error] [DBIUsageException trace uid:5c503a026f41a] #9 {main}
[gui:error] [DBIUsageException details uid:5c503a026f41a] "SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'saml_user_identification_uid' at row 1"
[gui:error] [DBIUsageException details uid:5c503a026f41a] Array
[gui:error] [DBIUsageException details uid:5c503a026f41a] (
[gui:error] [DBIUsageException details uid:5c503a026f41a]     [method] => execute
[gui:error] [DBIUsageException details uid:5c503a026f41a]     [args] => Array
[gui:error] [DBIUsageException details uid:5c503a026f41a]         (
[gui:error] [DBIUsageException details uid:5c503a026f41a]             [0] => Array
[gui:error] [DBIUsageException details uid:5c503a026f41a]                 (
[gui:error] [DBIUsageException details uid:5c503a026f41a]                     [:saml_user_identification_uid] => <saml:NameID xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" NameQualifier="https://myidp" SPNameQualifier="https://mysp" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent">pF9KBejleRvfe5g6FRVWlRiE420=</saml:NameID>
[gui:error] [DBIUsageException details uid:5c503a026f41a]                     [:saml_user_identification_uid_hash] => 6e179f1cbfe88410a2473388087c2b34548d1dbc
[gui:error] [DBIUsageException details uid:5c503a026f41a]                     [:created] => 2019-01-29 11:33:22
[gui:error] [DBIUsageException details uid:5c503a026f41a]                     [:last_activity] => 2019-01-29 11:33:22
[gui:error] [DBIUsageException details uid:5c503a026f41a]                     [:comment] =>
[gui:error] [DBIUsageException details uid:5c503a026f41a]                 )
[gui:error] [DBIUsageException details uid:5c503a026f41a]
[gui:error] [DBIUsageException details uid:5c503a026f41a]         )
[gui:error] [DBIUsageException details uid:5c503a026f41a]
[gui:error] [DBIUsageException details uid:5c503a026f41a]     [query] => INSERT INTO Authentications(saml_user_identification_uid, saml_user_identification_uid_hash, created, last_activity, comment) VALUES(:saml_user_identification_uid, :saml_user_identification_uid_hash, :created, :last_activity, :comment)
[gui:error] [DBIUsageException details uid:5c503a026f41a] )
[gui:error] [DBIUsageException details uid:5c503a026f41a]
```

**Comment by peter-** [comment]
```php
[:saml_user_identification_uid] => <saml:NameID xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" NameQualifier="https://myidp" SPNameQualifier="https://mysp" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent">pF9KBejleRvfe5g6FRVWlRiE420=</saml:NameID>
```
JFYI, the above seems to suggest the SP is misconfigured in that it's not properly serialising the AttributeValue of the eduPersonTargetedID attribute (i.e., a `NameID` XML structure) into its constituent parts, e.g. using SimpleSAMLphp's [NameIDAttribute](https://simplesamlphp.org/docs/stable/saml:nameidattribute) authproc filter. Using that you'd not only be able to rid the value of those spurious XML artefacts but you could also decide to drop the `SPNameQualifier` (i.e., this SP's own entityID which will be identical for any eduPersonTargetedID value recieved) completely and adopt a both simpler and shorter serialisation format (such as `%V!%I` or `%V@%I` as per the authproc filter's documentation, i.e. the subject-specific text value from the AttributeValue element + `!` or `@` + the asserting IDP's entityID).

Of course depending on IDP implementation and configuration that may still overflow 170 chars (though it would be worthwhile doing the above anyway). I don't recall whether SimpleSAMLphp supports something like the [Shibboleth SP's automatic hashing of attribute values](https://wiki.shibboleth.net/confluence/display/SP3/AttributeDecoder) (see `hashAlg` there) which would allow you to use a one-way function to "condense" possibly overly long identifier values to the length of the chosen hashing algorithm. Even if it doesn't I guess you could add a call to `hash('sha256', $str)` somewhere within SimpleSAMLphp (e.g. in a PHP authproc filter) or within Filesender configuration (which is just PHP code).

And of course you could also use the Shibboleth SAML SP implementation with Filesender, instead of SimpleSAMLphp. Not only will that do the serialisation for you out of the box, as indicated above it also allows easy hashing of attribute values (at the cost of losing the original identifier value in the one-way function).

**Comment by monkeyiq** [comment]
Some mysql/mariadb database versions in use still have the limitation of 767 bytes for the length of a column that has an index. Since we are dealing with utf we might use 4 octets for a character so 170 was the length of the field (less than the 191.75 max).

More recent database engines use DYNAMIC as the default row type which allows up to 3072 bytes to be indexed, so a 768 character string will fit into an index using utf8mb4 encoding.

The best way forward may be to see what options are needed on mariadb 10.0 or above to allow upto 768 character strings to be indexed and document that and try to make it easy to setup and check if your mariadb can handle these sizes. I don't recall having done anything special on mariadb 10.3 to be able to index columns of varchar(768). But we want to also make sure that mariadb 10.0 (as a min version) will be happy with the setup.

**Comment by monkeyiq** [comment]
You could change the 170 up to something like 760 in the authentication class and update your database. This should at least get you up and running with longer IDs.
https://github.com/filesender/filesender/blob/master/classes/data/Authentication.class.php#L56

It is a bit fiddly having to change those numbers when you upgrade.

**Comment by monkeyiq** [comment]
As mentioned above, I don't think a really general purpose solution to this can be made until such time as everybody is comfortable that they are using with PostgreSQL or a MariaDB version (and configuration) that allows secondary indexing on varchar() longer than 170 characters. That later point will happen in time but it might be a while until consensus is achieved (perhaps a few years) and until then I can't really change the default in FileSender to a higher value.
