### ISSUE TITLE
php 7.2 compatible?

### ISSUE THREAD

**Issue by madsi1m** [filesender/filesender#466]
Is filesender php 7.2 compatible? I noticed php 7.0 is now unsupported

**Comment by monkeyiq** [comment]
I have been running it on php 7.2.13 for a little while. I will be doing a bunch of updates so will post if I see anything not working on 7.2 (and likely fix it if that is the case while I am at it ;)

FWIW I test on the desktop against mariadb-10.3.11 and postgresql-server-10.6

The CI env uses php 7.0 and mariadb 10.0 (and postgresql too, but less specific on version) https://github.com/filesender/filesender/blob/master/.travis.yml#L5. Maybe we should bump the CI to php 7.2 instead of testing on an unsupported language version.

**Comment by monkeyiq** [comment]
so... now to update the docs!

**Comment by monkeyiq** [comment]
As mentioned in 488 above, the CI is now using php 7.2 to help ensure future compatibility.

**Comment by monkeyiq** [comment]
CI is now on php 7.2 and latest simplesamlphp along with using the vendor phpunit to avoid the incompatibility of selenium with some versions of phpunit.

So in short, php 7.2 is now the recommended version :)
