### ISSUE TITLE
Configuration transfer/guest options sanity check

### ISSUE THREAD

**Issue by jornane** [filesender/filesender#49]
We had an incident where FileSender became unusable after a guest options was added to the list of transfer options. When this happens, FileSender will still appear to work, but fail uploading with the error `{bad_option_name}`. The guest option does appear in the upload page.

FileSender should do better configuration checking, and fail to load the upload page in case there is something wrong with the options.

**Comment by monkeyiq** [comment]
It might be a little late to ask but do you have hints as to what options might have been added to trigger this?

**Comment by jornane** [comment]
Try any under http://docs.filesender.org/v2.0/admin/configuration/#guest_options

I haven't tried all, but any of the following should trigger said error:
`email_upload_started` `email_upload_page_access` `valid_only_one_time` `does_not_expire` `can_only_send_to_me` `email_guest_created` `email_guest_created_receipt` `email_guest_expired`

**Comment by monkeyiq** [comment]
I notice these are all the guest options -- https://github.com/filesender/filesender/blob/master/classes/constants/GuestOptions.class.php#L38

I just tested with all options other than "get a link" set to true and it seems to be ok now. Perhaps some of the recent merges to guest option handling have helped things. Perhaps I'm using a slightly different configuration that doesn't want to trigger the bug :/

I did notice this message during my hacking if I allowed an option to be set that wasn't there before. So I've seen the glory of the message you mention (not so great for a guest to see). But that was caused by me adding a new option on the guest page for testing.
