### ISSUE TITLE
Upload stuck at 100%

### ISSUE THREAD

**Issue by anahimself** [filesender/filesender#593]
Hello,

I am using apparently  of filesender, and it worked very well but we recently discovered that everytime a user uploads a file with IE, it is stuck @ 100% and nothing more happen.

This is working very well with Firefox and Chrome

This is known bug by any chance ? (we tried to upgrade the filesender, but a lot of problems with css/theme with some browsers)

Regards,

**Comment by madsi1m** [comment]
Which version of IE?
Which version of filesender?

**Comment by anahimself** [comment]
IE 11
Version 1.6.1 commented in source code

Several users explained that to us, always with IE (and always reproductiole)

**Comment by anahimself** [comment]
No error in console apparently, and the "popup" with the progress of download is stuck @ 100% and nothing more happens.

**Comment by monkeyiq** [comment]
I am wondering if 1.6.1 commented in source code means that you are using the 1.6.1 release of FileSender from 30.Dec.2015? There have been some bugs fixed that could lead to the behavior you mention if you are running an older FileSender.

I just did a few uploads using IE11 on Windows 10 (using git master of FileSender). A small upload of 30 bytes, a 5mb file and a 45mb file all of which completed. This is over a LAN etc so might not be replicating the issue. I am using IE 11.239.18362.0 on update version 11.0.135. I suspect IE11 on windows 10 is also somewhat different to IE11 on Windows 7 so that is another factor.

**Comment by monkeyiq** [comment]
I am not sure that issues with upload in 1.x series FileSender will be addressed. If there are issues in a recent version please report them as new issues on this github project page.

**Comment by anahimself** [comment]
It was related to IE switching to compatibility mode (this happens when a website is in intranet zone)

We added a meta tag to allow IE11 to run this and problem got away

`<meta http-equiv="X-UA-Compatible" content="IE=edge" />`

**Comment by monkeyiq** [comment]
Thank you for this information! If this is causing a problem in recent releases I could make FileSender output that tag for IE11 as a configuration option.

**Comment by anahimself** [comment]
You should yes, it was breaking also a lot of stuff in newer versions (this
is why we did not go to the latest version)

Now that we found it, we will see :)
