### ISSUE TITLE
Can't easily resume interrupted upload

### ISSUE THREAD

**Issue by peter-** [filesender/filesender#600]
If an upload is being interrupted due to "vis major" (e.g. your ISP or ADSL/cable model having issues, your WiFi being down or just out of reach, you fat-fingering your Ethernet cable out of the socket, etc.) there's no obvious way to resume such an upload, AFAICT:  
Once my network connection was interrupted no amount of hitting `pause`/`resume` will cause the upload to continue and the only other button being offered is `stop`, kindly offering to "remove already uploaded data" which is the least desirable option. (Imagine you're at 98% of a 100GB file when this happens, as such things tend to go.)

What seems to happen in such cases though is that the `nothing_happened_as_of_late_you_can_send_client_logs` message is shown at some point (after several minutes of inactivity) and I am being offered a button to `Send logs` somewhere unspecified. Clicking that button causes the following things to happen (Firefox 68):

* Render a (FF-specific?) JS overlay/popup with the text "This page is asking you to confirm that you want to leave - data you have entered may not be saved" offering the two choices `Stay on page` and `Leave page`. Picking either one does *not* send any logs anywhere from looking at the server's MTA's logs (on a machine fully configured with Filesender sending emails successfully otherwise).
* Even *before* chosing between those two options below the overlay I can see a green "Logs successfully sent" message when in fact nothing has been sent (AFAICT).
* Clicking `Stay on page` does not seem to do anything (which is probably expected but non-obvious given the browser's generic  and possibly unfortunate -- warning about potentially losing data when leaving the page).
* Clicking `Leave page` finally brings up yet another dialog asking me to "Restart failed transfer?". That now offers three buttons to click, the one for resuming the transfer now being called `Load failed transfer` (maybe overly literally), the other two being `Forget about it` and `Ask me again later`. "Forget about it" means "remove already uploaded data" (as it was put before then clicking the `stop` button) but is phrased phrased differently and somewhat ambiguous. (If you let me delete all my uploaded  data I'd appreciate being clear about this.)
* So eventually chosing `Load failed transfer` one can resume the interrupted upload (by re-selecting the same files as before and re-starting the upload, as one is being informed).  
Though initially German language was detected/selected in the browser at the time I encountered this issue and the translation for that button is wrong/highly misleading, stating `Laden des Dateitransfers fehlgeschlagen`, i.e., "Loading of file transfer [has] failed" literally. I couldn't imagine what a button with this description would do (as it simply informed me that the transfer has failed, which I already knew) but it certainly didn't sound like it would help me resume the intererrupted transfer, and so did "Vergiss es" (Forget it), though correctly in the latter case. ;)

Issues
--------

I've lumped a few things into this narrative, feel free to spin off separate issues from these, though:

* Pause/resume cannot resume a transfer that was interrupted
* The workaround to restart such transfers only appears after inactivity has been detected and even then is fraught with popups and dialogs which are not all that obvious to navigate.
* `Send logs` did noting for me, though a green overlay said "Logs successfully sent"
* German translation for message `load` is wrong/misleading  
(The -- again, overly literal -- correct translation would be `Fehlgeschlagenen Dateitransfer laden", though personally I'd suggest to consistently relabel this with something that suggests this is the way to resume the failed transfer in all languages.)

Workaround
---------------

Seems one can re-start the failed transfer immediately *if* one simply enters the filesender URL again into the browser bar -- fearlessly clicking "Leave page" in FF's dialog warning me about data loss -- in the process. Then the overlay/pop-up with the three somewhat unusually labelled buttons to restart the transfer is shown immediately, avoding having to wait for the "nothing happenend" timer to expire.

**Comment by peter-** [comment]
FWIW, I had made a short screen recording demonstrating all of the above but ultimately Github didn't allow the file extension (`.webm`) so I couldn't include it here. Hence all the text above. Sigh.

**Comment by monkeyiq** [comment]
I did some sniffing around before trying to find a "network lost" type message that the browser could pickup. It seems like a generally handy concept that the browser could communicate that web pages might like to know about. The related "have network again" message would be great too.. I didn't turn up any such events at the time, though maybe I missed it. I was testing on laptops where I dropped wifi and the like to see what would happen. I think we should improve how such stalls are handled. 

One of the downsides to automatic stall detection is that if it is too aggressive it can stall uploads on slower pipes. Generally a resume will restart by sending from the start of the a chunk, so if you have 4mb chunks and a slower network connection and temporarily drown out the upload traffic then the chunk might keep spinning in a resume cycle. You send 1mb then it stalls for $time and filesender restarts the chunk and you send 2mb slowly enough for it to be considered a stall and the chunk is again restarted.

In release version 2.5 the terasender_worker_xhr_timeout configuration directive was added as an additional timeout when data was not sent for a given number of milliseconds. Though it was found that the released setting was too low for busy conference wifi and caused false positives for stall detection (turns out data was completely stalled for 20+ seconds at those sites). This led to an errata lifting the default value to an hour. It may be that using a more aggressive setting again, with progressive backoff would be the best move. Offer fast resume for most cases and fewer false positives due to backoff for wifi which could have wildly varying characteristics.

It might be useful for the user interface to offer a well worded "resume" type button for cases where you moved the laptop to a different AP or bumped the cable and know you want to explicitly resume right now.

I will have a more in depth look at the code and related config directives shortly.

**Comment by monkeyiq** [comment]
I have been working on and testing out https://github.com/filesender/filesender/pull/609 by forcing the wifi connection off on a laptop and seeing how things respond. There are still times when it is slow to recover once the network is up but it does come back and there is a "reconnect" type button there to force a resume at any time now. I have tried to work out a way to massage the "reconnect" into the existing controls but it is different enough to a normal pause/resume that I think it should exist in it's own right.

**Comment by monkeyiq** [comment]
With https://github.com/filesender/filesender/pull/610 the code now also pauses the upload when too many attempts to restart have happened. This should avoid multiple dialogs from appearing in that case.

**Comment by monkeyiq** [comment]
Looking back at the top post, the new "reconnect and Continue" button should solve the issue that the upload couldn't be explicitly resumed after network drop. 

There are other sub parts in this issue which I might break out into specifc issues, such as verifying that send client logs does something or reports to the user that it has failed.

**Comment by FrankFeng** [comment]
Hi @monkeyiq 

I am using fileSender (via a voucher) to upload files. What I see is in the attached picture below, and there is no "reconnect and Continue" button:

![fileSender](https://user-images.githubusercontent.com/4476144/73702230-01add200-473c-11ea-804f-b9791cc0a246.png)

**Comment by monkeyiq** [comment]
@FrankFeng you should see the reconnect and continue in the place the "Send" button is in your screen shot, but it only appears sometimes. In the below I have started an upload and then paused the upload and see many options. I am still not 100% happy with having a resume and a "reconnect and continue" in there as these are very similar from a user perspective but resume will try to resume active upload workers where as "reconnect and continue" closes internal workers and remakes them to force new TCP connections to be made. In short "reconnect and continue" is a very strong resume.

![reconnect and continue](https://user-images.githubusercontent.com/387108/73736354-5d07b080-478c-11ea-8cb7-d15c38059cdb.png)

**Comment by FrankFeng** [comment]
Thanks @monkeyiq  !

**Comment by WebSpider** [comment]
This issue has been fixed since 2020
