### ISSUE TITLE
Bad REST parameter when adding recipient at existing transfer. (aup check failed)

### ISSUE THREAD

**Issue by fransward** [filesender/filesender#681]
When a user tries to add a new recipient to an existing transfer (option under My transfers tab), a error is shown:

> Bad REST parameter
> {method}: post
> {endpoint}: transfer

The logs indicate that the AUP is not checked. Which is a perfectly sane error when you have the must_check_AUP setting enabled.

> [2019-11-11 15:53:13] [rest:debug] /usr/share/filesender/filesender-2.61/www/rest.php:37 RestServer::process() Forwarding call to RestEndpointTransfer::post() handler
> [2019-11-11 15:53:13] [user 15] [rest:warn] nefarious activity suspected: A user with id 15 has sent a request without AUP data checked and is likely doing something bad.
> [2019-11-11 15:53:13] [user 15] [rest:error] [RestBadParameterException exception uid:5dc975d9e7c76] rest_bad_parameter
> [2019-11-11 15:53:13] [user 15] [rest:error] [RestBadParameterException trace uid:5dc975d9e7c76] #0 /usr/share/filesender/filesender-2.61/classes/rest/RestServer.class.php(303): RestEndpointTransfer->post('301', 'recipient')
> [2019-11-11 15:53:13] [user 15] [rest:error] [RestBadParameterException trace uid:5dc975d9e7c76] #1 /usr/share/filesender/filesender-2.61/www/rest.php(37): RestServer::process()
> [2019-11-11 15:53:13] [user 15] [rest:error] [RestBadParameterException trace uid:5dc975d9e7c76] #2 {main}
> [2019-11-11 15:53:13] [user 15] [rest:error] [RestBadParameterException details uid:5dc975d9e7c76] method = "post"
> [2019-11-11 15:53:13] [user 15] [rest:error] [RestBadParameterException details uid:5dc975d9e7c76] endpoint = "transfer"
> [2019-11-11 15:53:13] [user 15] [rest:error] [RestBadParameterException details uid:5dc975d9e7c76] parameter = "aup_checked"

**Comment by monkeyiq** [comment]
This is a bit strange, if you have the following in config.php you shouldn't be able to upload without checking the aup.
```
$config['aup_enabled'] = true;
```

I think a user should be able to add new recipients to a transfer with AUP because they have already agreed to the AUP when uploading the file. With aup_enabled=true I can only upload after checking the aup and can add new recipients to an existing transfer.

Digging into the code a little this specific error should only be thrown when the transfer id is not provided to the REST end point. That is the case when creating a new transfer. If the code is modifying something then the code provides the tranferid to modify and the aup check should be disabled as the transfer has already been created. Set at https://github.com/filesender/filesender/blob/master/classes/rest/endpoints/RestEndpointTransfer.class.php#L357 used at https://github.com/filesender/filesender/blob/master/classes/rest/endpoints/RestEndpointTransfer.class.php#L369
 
I assume you get this error when you create a new upload (after checking the aup) and then try to add a new recipient to that transfer on the my transfers page. If that is the case could you test with
```
console.log('id is ' + id);
```
on line https://github.com/filesender/filesender/blob/master/www/js/transfers_table.js#L74 and see if there is a numeric id shown on the browser console. That printed id should be the Transfers.id in the database.

**Comment by monkeyiq** [comment]
If this is happening still (or for others) please reopne the issue.
