### ISSUE TITLE
Not null violation when migrating database on PostgreSQL

### ISSUE THREAD

**Issue by jornane** [filesender/filesender#72]
When trying to run the database migration script on PostgreSQL after #63, I get the following error:

```
"SQLSTATE[23502]: Not null violation: 7 ERROR:  column "reminder_count" contains null values"
```

The field is set to be not-null, but a default value was not specified.  
Either provide a `default` value or set `null` to `true`.

MySQL is less strict about these things and the migrations script works fine there.

**Comment by monkeyiq** [comment]
I made the above PR want the reminder_count to be not null and 0 by default. If anyone has columns by other definitions then maybe the simpler way is to drop those columns and recreate them with the database.php script.

```
psql filesender
alter table guests drop column last_reminder ; 
alter table guests drop column reminder_count ;
alter table recipients drop column last_reminder ;        
alter table recipients drop column reminder_count ;
```

I think going forward that is the better option rather than allowing null and defaulting to 0 to try to allow looser schema that might exist in the current git master env.

**Comment by monkeyiq** [comment]
@jornane sorry about the delay getting this mainline.
