### ISSUE TITLE
E-mail fields not visible on upload page

### ISSUE THREAD

**Issue by richardvliegen** [filesender/filesender#828]
Hi, 

I can succesfully login via SimpleSample to the Filesender application, but the mail fields are not visible. When i check the code in chrome, it says that their hidden, but nowhere i can find how to make them visible.

![no fields](https://user-images.githubusercontent.com/69194815/89279867-2d0c6d80-d648-11ea-8876-6c3a7e03b798.PNG)

![elements](https://user-images.githubusercontent.com/69194815/89280118-752b9000-d648-11ea-8eeb-01c3d213da66.PNG)

**Comment by monkeyiq** [comment]
Which version of Chrome and FileSender? As a long shot, in the Network tab was a file not found during the page load?

Using FileSender version git development (almost identical to last release) and Chrome 83.0.4103.116 it appears here.

**Comment by richardvliegen** [comment]
Hi, 

We have chrome version Version 84.0.4147.105 (Official Build) (64-bit) en filesender latest (from GIT)

This is the output from the network tab

![network tab](https://user-images.githubusercontent.com/69194815/89496297-66fd8100-d7ba-11ea-8d37-6d5749602665.PNG)

It seems that Filesender see's me as a guest, instead of an authenticated user, but we are connected via LDAP.

**Comment by monkeyiq** [comment]
For a while I have felt that parts of the UI are not very obvious. There is a new UI2 on the horizon so I have left some things as they have been. 

One area that is not obvious in the current user interface is that having "Get a link instead of sending to recipients" makes the email mail fields hidden. Does deselecting that "get a link" option change the fields to be shown? If not this would be the first place to start digging into why.

**Comment by meijer** [comment]
Richard, the email fields are not visible because the FileSender installation you're using has 'Get a link instead of sending to recipients' set as a default-on option. If you're the admin, check the config file and look for transfer_options. Tweak that to how you'd like it to behave:

https://docs.filesender.org/v2.0/admin/configuration/#transfer_options

@Ben, perhaps an idea to change that in the default config file? Unsure with the new UI coming though.


cheers,
Jan

**Comment by richardvliegen** [comment]
Hi Jan, 

thanks, in my config file (config.php) i can't find any transfer options. Am i looking in the correct file?

Thanks
Richard

**Comment by richardvliegen** [comment]
Hi, thanks, this has been fixed 👍 

only, when i send an email, it is not arriving to the recipient.

**Comment by meijer** [comment]
Good to hear it's fixed. 

Did you check the email logs on the FS server to see if the email leaves there? There is also a chance the email ended up in the recipient's spam folder.

**Comment by richardvliegen** [comment]
Hi, mail is also fixed by installing postfix. 

1 other question; in which file i can remove languages from the header? i just want English, Dutch, French and German. Thanks

**Comment by meijer** [comment]
Good to hear mail is fixed. 

On language configuration: 
https://docs.filesender.org/v2.0/i18n/

It's been a while since I've done this myself, but I think this was it:

"One can select available languages and their names by creating a config/language/locale.php file (same structure as language/locale.php)."

So, just create a file config/language/locale.php with the languages you want, and follow the structure you find in the folder /language/locale.php. 

If you don't mind me asking, for what kind of organisation/community are you setting up a filesender installation?

**Comment by WebSpider** [comment]
Is this issue still valid, or can this be closed?

**Comment by monkeyiq** [comment]
This seems to be fixed given the references above. If not, please reopen :)
