### ISSUE TITLE
javascript errors

### ISSUE THREAD

**Issue by files01** [filesender/filesender#839]
Hello,

It is the first time i launch filesender, i can login and simplesaml is ok.

My browser is firefox 80.0.1. i have an error the lastest release Uncaught SyntaxError: '' literal not terminated before end of script filesender-config.js.php:83:16

an extract of the end of the script :
    valid_filename_regex: '^[ \\/\\p{L}\\p{N}_\\.,;:!@#$%^&*)(\\]\\[_-]+$',
    base_path: '/filesender/',
    support_email: '',
    autocomplete: {
        enabled:  false,
        min_characters: 3
    },
    message_can_not_contain_urls_regex: '',

    auditlog_lifetime: 31,
    
    logon_url: '

Do you have the same issues ? The javascript don't load completly ?

**Comment by monkeyiq** [comment]
When I have seen this issue in the past it has had to do with something in my config.php causing filesender-config.js.php not to show valid json. One way to narrow this down is to load the url with /filesender-config.js.php in your browser and see where the page stops or produces bad output. 

It appears from your above that the support_email starts a double quote but is not terminated. Try changing the value of support_email in your config.php to see if it allows filesender-config.js.php to load completely. This may also result in a validity check being added to FileSender to help catch this issue for future deployments.

**Comment by files01** [comment]
It's seems to be the variable logon_url in the javascript. I try to set this variable in config.php but it is the same error. I try to modify the javascript !!!

**Comment by files01** [comment]
I comment this line in filesender-config.js.php and after i have no more errors

    logon_url: '<?php // echo AuthSP::logonURL() ?>',
    logoff_url: '<?php // echo AuthSP::logoffURL() ?>',

**Comment by monkeyiq** [comment]
As you mentioned using simplesaml above, the logonURL should eventually be calling into logonURL() and using http_build_query in the call at: https://github.com/filesender/filesender/blob/7c08ee83c4c81c5318067ebf6472be44625bb667/classes/auth/AuthSPSaml.class.php#L207

I wonder if the strings self::$config['authentication_source'], $target, and, self::$config['simplesamlphp_url'] look sane at that point. The following would help you see them, as they relate to authentication (and your server) you might like to just inspect them privately at first to see that they are valid rather than posting them here.

```
Logger::error( 'authentication_source ' . self::$config['authentication_source'] );
Logger::error( 'target ' . $target );
Logger::error( 'simplesamlphp_url ' . self::$config['simplesamlphp_url'] );
```

**Comment by monkeyiq** [comment]
Feel free to add any additional information that might help others. Until then I might mark this as closed.
