### ISSUE TITLE
Possible nodejs REST client

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#861]
If there was a REST client using nodejs then the crypto code (javascript) might also be used by that rest client. If there was a WebCrypto API implementation that could be used in nodejs it would allow the creation of encrypted uploads from the command line and the downloading and decrypting of encrypted transfers from the command line.

**Comment by peter-** [comment]
Just a thought: Since nodejs won't be easily available everywhere (the way Python is) and since such a project would probably pull in quite a few dependencies, wrapping that all up into a docker container would probably help people deploying this client.
(To the extent that people rather deploy docker than nodejs, which may not universally be the case, of course.)

**Comment by monkeyiq** [comment]
There is now a proof of concept uploading an encrypted file from the command line using nodejs

https://github.com/monkeyiq/filesender/tree/2023/apr/jsrestclientpoc
