### ISSUE TITLE
Allow files to be sent from the local filesystem that the server is running on.

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#930]
For example if FileSender is on a NAS you might like to just send a big file and have the web link made available without needing to download the file and upload it again. 

This has two primary parts:
* privilege escalation (web user to local system user account) 
* file selection custom storage backend for download. The storage backend would allow the file to be read directly from the home directory rather than copied to the filesender "files" area.

**Comment by jowagner** [comment]
Another problem of serving a file from outside the storage under FileSender's control is that the file may change, be removed or have unsuitable permissions.

If the goal is to reduce the upload time one could copy the file (lightweight CoW can be used with suitable filesystems) on the NAS to a location under FileSender's control.

The feature described in the title could also be implemented without requiring the user to specify the location on the NAS: The client could obtain a fingerprint of the file (or each chunk of the file) and ask the server whether the file or chunk is known already before sending it.

**Comment by peter-** [comment]
This functionality has been available since 2016, cf. [scripts/client/createtransfer.php](https://github.com/filesender/filesender/tree/development/scripts/client/createtransfer.php) as also [discussed](https://sympa.uninett.no/lists/filesender.org/arc/filesender-dev/2020-12/msg00001.html) on the mailing list.

If this satisfies your requirements please close this issue. If it doesn't please suggest specific improvements.
